
name: Helm Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            role-to-assume:        arn:aws:iam::774305579778:role/eks-admin-role
            aws-region:            ${{ secrets.AWS_REGION }}


      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{secrets.EKS_CLUSTER_NAME}}

      - name: Helm deploy auth
        run: |
          helm upgrade --install auth helm/auth --namespace dev
            --set image.tag=${{ github.sha }}


      - name: Helm deploy auth
        run: |
          
          helm upgrade --install orders helm/orders --namespace dev --set image.tag=${{ github.sha }}

      - name: Helm deploy auth
        run: |
          helm upgrade --install payment helm/payment --namespace dev --set image.tag=${{ github.sha }}


      - name: Deploy ingress (dev)
        run: |
          kubectl apply -f k8s/ingress-dev.yml

