name: Terraform Platform

on:
  workflow_call:

jobs:
  platform:
    runs-on: ubuntu-latest
    env:
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Terraform Cloud
        run: |
          echo 'credentials "app.terraform.io" {
            token = "${{ secrets.TFC_TOKEN }}"
          }' > ~/.terraformrc

      - name: Terraform Init
        working-directory: terraform/platform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/platform
        run: terraform apply -auto-approve
