name: Terraform Workload

on:
  workflow_call:

jobs:
  workload:
    runs-on: ubuntu-latest
    env:
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (assume role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume:        arn:aws:iam::774305579778:role/eks-admin-role
          aws-region:            ${{ secrets.AWS_REGION }}  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Terraform Cloud
        run: |
            echo 'credentials "app.terraform.io" {
              token = "${{ secrets.TFC_TOKEN }}"
            }' > ~/.terraformrc

      - name: Terraform Init
        working-directory: terraform/workload
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/workload
        run: terraform apply -auto-approve
